apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-api-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: product-api
  namespaceSelector:
    matchNames:
      - devops-demo
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
