apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      serviceAccountName: default # Ensure this SA has IAM permissions for SSM
      containers:
        - name: product-api
          image: AWS_ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/product-api:IMAGE_TAG
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: product-api-svc
  namespace: devops-demo
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
